language: node_js
notifications:
  email: false
node_js:
  - '10'

# S: Build Lifecycle
install:
  - npm install
before_script:
  - echo "start"
script:
  - npm run build && npx gh-pages --branch gh-pages --repo https://"$GH_TOKEN"@github.com/AngusFu/webgl-guide-reading.git  -d ./docs

after_script:
  - echo "done"
# E: Build LifeCycle

after_success:
  - echo Done
branches:
  - master
