language: node_js
notifications:
  email: false
node_js:
  - '10'

# S: Build Lifecycle
install:
  - npm install
before_script:
  - echo "start"
script:
  - npm run publish
after_script:
  - echo "done"
# E: Build LifeCycle

after_success:
  - echo Done
branches:
  - master
